# improve colors
set -g default-terminal 'screen-256color'

# size windows based on clients looking at that window
setw -g aggressive-resize on

# enable mouse control
set -g mouse on

# start window numbers at 1 to match keyboard order with tmux order
set -g base-index 1

# start pane numbers at 1 to match keyboard order with tmux order
setw -g pane-base-index 1

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# monitor windows for activity
setw -g monitor-activity on

# display pane numbers for longer
set -g display-panes-time 2000

set -g status-left-length 20

# increase scrollback lines
set -g history-limit 65536
